[package]
name = "pydataclass"
version = "0.1.0"
edition = "2024"

[dependencies]
pretty = "0.12.4"
pydataclass-derive = { path = "pydataclass-derive" }

[workspace]
members = [
  "pydataclass-derive"
]

[[example]]
name = "basic"
